/**
 * Default accounting categories for a driving school business.
 *
 * Each category carries full accounting metadata:
 * - accountType      (income / expense / asset / liability / equity)
 * - statementType    (p_and_l / balance_sheet / equity_movement / tax_control)
 * - reportingBucket  (sub-grouping on the financial statement)
 * - defaultTaxTreatment + defaultVatRate + defaultVatRecoverable
 *
 * Notes on UK tax treatment for driving schools:
 * - Driving tuition is EXEMPT from VAT (HMRC Notice 701/30)
 * - Most purchases from VAT-registered suppliers carry 20% standard rate
 * - Books / printed learning materials are zero-rated
 * - Insurance is exempt (no VAT)
 * - Vehicle Tax (road tax) is outside scope of VAT
 * - Bank charges are exempt
 * - Drawings and Capital are outside scope (equity, not commercial supply)
 */

import type { CategoryRule } from "@/lib/domain/types";

export const DRIVING_SCHOOL_CATEGORIES: CategoryRule[] = [
  // ── INCOME ─────────────────────────────────────────────────────────────────
  {
    id: "cat_lesson_income",
    category: "Lesson Income",
    supplierPattern: "",
    keywordPattern: "lesson|tuition|instruction|pupil|student",
    priority: 5,
    accountType: "income",
    statementType: "p_and_l",
    reportingBucket: "Income",
    defaultTaxTreatment: "exempt",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "4000",
    isActive: true,
    allowableForTax: true,   // income is always taxable
    allowablePercentage: 100,
  },
  {
    id: "cat_other_income",
    category: "Other Income",
    supplierPattern: "",
    keywordPattern: "",
    priority: 90,
    accountType: "income",
    statementType: "p_and_l",
    reportingBucket: "Income",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: false,
    glCode: "4900",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },

  // ── MOTOR EXPENSES ─────────────────────────────────────────────────────────
  {
    id: "cat_fuel",
    category: "Fuel",
    supplierPattern: "bp|shell|esso|texaco|sainsbury.*fuel|tesco.*fuel|asda.*fuel|morrisons.*fuel|moto|welcome break",
    keywordPattern: "fuel|petrol|diesel",
    priority: 10,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "5100",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_insurance",
    category: "Insurance",
    supplierPattern: "aviva|admiral|direct line|axa|zurich|churchill|comparethemarket|go compare|ageas|hastings",
    keywordPattern: "insurance|insure",
    priority: 11,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "exempt",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "5110",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_repairs_maintenance",
    category: "Repairs & Maintenance",
    supplierPattern: "kwik fit|halford|autocentre|garage|mot|halfords",
    keywordPattern: "repair|service|mot|tyre|tyres|brake|maintenance|mechanic|oil change",
    priority: 12,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "5120",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_vehicle_tax",
    category: "Vehicle Tax",
    supplierPattern: "dvla|driver and vehicle",
    keywordPattern: "vehicle tax|road tax|dvla",
    priority: 13,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "5130",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_car_cleaning",
    category: "Car Cleaning",
    supplierPattern: "car wash|valet",
    keywordPattern: "car wash|valet|cleaning|polish",
    priority: 14,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "5140",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_parking_tolls",
    category: "Parking & Tolls",
    supplierPattern: "ncp|q-park|dart charge|dart crossing",
    keywordPattern: "parking|toll|congestion|dartford",
    priority: 15,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "5150",
    isActive: true,
    allowableForTax: true,   // legitimate parking/tolls are allowable; fines should be a separate category
    allowablePercentage: 100,
  },
  {
    id: "cat_parking_fines",
    category: "Parking Fines",
    supplierPattern: "pcn|penalty charge|parking fine|council",
    keywordPattern: "fine|penalty|pcn|fixed penalty",
    priority: 16,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Motor Expenses",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "5160",
    isActive: true,
    allowableForTax: false,  // HMRC: fines & penalties are NOT allowable
    allowablePercentage: 0,
  },

  // ── ADMIN EXPENSES ─────────────────────────────────────────────────────────
  {
    id: "cat_phone",
    category: "Phone",
    supplierPattern: "o2|vodafone|three|ee|bt|virgin mobile|sky mobile|giffgaff",
    keywordPattern: "phone|mobile|broadband|internet|sim",
    priority: 20,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "6100",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_advertising",
    category: "Advertising",
    supplierPattern: "google|facebook|meta|instagram|nextdoor|yell",
    keywordPattern: "advertising|marketing|advert|promotion|social media|google ads",
    priority: 21,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "6110",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_accountancy",
    category: "Accountancy Fees",
    supplierPattern: "",
    keywordPattern: "accountant|accountancy|bookkeeping|tax return|self assessment",
    priority: 22,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "6120",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_training_materials",
    category: "Training Materials",
    supplierPattern: "dvsa|dsa|theory test",
    keywordPattern: "training material|hazard perception|theory|highway code|book|dvsa",
    priority: 23,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "zero_rated",
    defaultVatRate: 0,
    defaultVatRecoverable: true,
    glCode: "6130",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_office_supplies",
    category: "Office Supplies",
    supplierPattern: "staples|ryman|viking|amazon|currys",
    keywordPattern: "stationery|office supplies|printer|paper|ink|supplies",
    priority: 24,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "6140",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_software_subs",
    category: "Software & Subscriptions",
    supplierPattern: "aws|amazon web|google cloud|microsoft|adobe|xero|quickbooks|dropbox|zoom|slack",
    keywordPattern: "software|subscription|saas|cloud|hosting|licence|license",
    priority: 25,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Admin & Office Expenses",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "6150",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },

  // ── FINANCE CHARGES ────────────────────────────────────────────────────────
  {
    id: "cat_bank_charges",
    category: "Bank Charges",
    supplierPattern: "barclays|lloyds|natwest|hsbc|santander|monzo|starling|revolut",
    keywordPattern: "bank charge|account fee|transaction fee|bank fee",
    priority: 30,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Finance Charges",
    defaultTaxTreatment: "exempt",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "7100",
    isActive: true,
    allowableForTax: true,
    allowablePercentage: 100,
  },
  {
    id: "cat_loan_interest",
    category: "Loan Interest",
    supplierPattern: "",
    keywordPattern: "interest|loan charge|finance charge",
    priority: 31,
    accountType: "expense",
    statementType: "p_and_l",
    reportingBucket: "Finance Charges",
    defaultTaxTreatment: "exempt",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "7110",
    isActive: true,
    allowableForTax: true,   // interest on business loans is allowable
    allowablePercentage: 100,
  },

  // ── FIXED ASSETS ───────────────────────────────────────────────────────────
  {
    id: "cat_vehicle_purchase",
    category: "Vehicle Purchase",
    supplierPattern: "",
    keywordPattern: "vehicle|car purchase|buy car|deposit|ford|vauxhall|volkswagen|vw|toyota|peugeot",
    priority: 40,
    accountType: "asset",
    statementType: "balance_sheet",
    reportingBucket: "Fixed Assets",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "0100",
    isActive: true,
    allowableForTax: false,  // Capital expenditure — not a revenue expense (use AIA/capital allowances separately)
    allowablePercentage: 0,
  },
  {
    id: "cat_equipment",
    category: "Equipment",
    supplierPattern: "",
    keywordPattern: "equipment|dashcam|dual control|brake|mirror",
    priority: 41,
    accountType: "asset",
    statementType: "balance_sheet",
    reportingBucket: "Fixed Assets",
    defaultTaxTreatment: "standard_rated",
    defaultVatRate: 20,
    defaultVatRecoverable: true,
    glCode: "0200",
    isActive: true,
    allowableForTax: false,
    allowablePercentage: 0,
  },

  // ── LIABILITIES ────────────────────────────────────────────────────────────
  {
    id: "cat_loan_received",
    category: "Loan Received",
    supplierPattern: "",
    keywordPattern: "loan|borrow|finance received|credit",
    priority: 50,
    accountType: "liability",
    statementType: "balance_sheet",
    reportingBucket: "Loans",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "2100",
    isActive: true,
    allowableForTax: false,
    allowablePercentage: 0,
  },
  {
    id: "cat_loan_repayment",
    category: "Loan Repayment",
    supplierPattern: "",
    keywordPattern: "loan repayment|repayment|finance payment",
    priority: 51,
    accountType: "liability",
    statementType: "balance_sheet",
    reportingBucket: "Loans",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "2100",
    isActive: true,
    allowableForTax: false,
    allowablePercentage: 0,
  },

  // ── EQUITY ─────────────────────────────────────────────────────────────────
  {
    id: "cat_drawings",
    category: "Drawings",
    supplierPattern: "",
    keywordPattern: "drawings|personal|owner withdrawal|proprietor",
    priority: 60,
    accountType: "equity",
    statementType: "equity_movement",
    reportingBucket: "Drawings",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "3200",
    isActive: true,
    allowableForTax: false,  // Owner drawings are NOT a business expense
    allowablePercentage: 0,
  },
  {
    id: "cat_capital_introduced",
    category: "Capital Introduced",
    supplierPattern: "",
    keywordPattern: "capital|owner contribution|proprietor capital|introduced",
    priority: 61,
    accountType: "equity",
    statementType: "equity_movement",
    reportingBucket: "Capital",
    defaultTaxTreatment: "outside_scope",
    defaultVatRate: 0,
    defaultVatRecoverable: false,
    glCode: "3000",
    isActive: true,
    allowableForTax: false,
    allowablePercentage: 0,
  },
];

/** Returns a DRIVING_SCHOOL_CATEGORIES item by category name, or undefined */
export function findDefaultCategory(name: string): CategoryRule | undefined {
  return DRIVING_SCHOOL_CATEGORIES.find(
    (c) => c.category.toLowerCase() === name.toLowerCase(),
  );
}

/** All unique reporting buckets in the driving school presets */
export const DEFAULT_REPORTING_BUCKETS: string[] = Array.from(
  new Set(DRIVING_SCHOOL_CATEGORIES.map((c) => c.reportingBucket)),
).sort();

/** All unique account types in the driving school presets */
export const DEFAULT_ACCOUNT_TYPES = ["income", "expense", "asset", "liability", "equity"] as const;
