import type {
  BankStatement,
  BankTransaction,
  CategoryRule,
  GlCodeRule,
  MappingTemplate,
  MatchDecision,
  ReconciliationRun,
  ReviewAction,
  UploadedFileMeta,
  User,
  VatRule,
  Workspace,
} from "@/lib/domain/types";
import { appConfig } from "@/lib/config";
import { DRIVING_SCHOOL_CATEGORIES } from "@/lib/accounting/default-categories";

const user: User = {
  id: "user_demo_owner",
  email: appConfig.demoCredentials.email,
  name: "Maya Chen",
};

const workspace: Workspace = {
  id: appConfig.workspaceId,
  name: "Northstar Finance",
  slug: appConfig.workspaceSlug,
  defaultCurrency: "GBP",
  countryProfile: "GB",
  amountTolerance: 1.5,
  dateToleranceDays: 5,
  vatRegistered: false,
  businessType: "sole_trader",
};

const vatRules: VatRule[] = [
  {
    id: "vat_gb_standard",
    countryCode: "GB",
    rate: 20,
    taxCode: "GB20",
    recoverable: true,
    description: "UK standard rate",
  },
  {
    id: "vat_gb_zero",
    countryCode: "GB",
    rate: 0,
    taxCode: "GB0",
    recoverable: true,
    description: "UK zero rate",
  },
  {
    id: "vat_ie_standard",
    countryCode: "IE",
    rate: 23,
    taxCode: "IE23",
    recoverable: true,
    description: "Irish standard rate",
  },
];

const aprilBankTransactions: BankTransaction[] = [
  {
    id: "bank_txn_uber",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "confirmed",
    sourceLineNumber: 12,
    transactionDate: "2026-04-02",
    amount: -42.6,
    currency: "GBP",
    merchant: "Uber BV",
    description: "Client visit taxi",
    employee: "Maya Chen",
    reference: "UBR-7741",
  },
  {
    id: "bank_txn_costa",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "confirmed",
    sourceLineNumber: 13,
    transactionDate: "2026-04-02",
    amount: -6.4,
    currency: "GBP",
    merchant: "Costa Coffee",
    description: "Team coffee before client workshop",
    employee: "Maya Chen",
    reference: "CST-281",
  },
  {
    id: "bank_txn_aws",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "suggested_match",
    sourceLineNumber: 17,
    transactionDate: "2026-04-04",
    amount: -91.12,
    currency: "USD",
    merchant: "Amazon Web Services",
    description: "Monthly hosting",
    employee: "No cardholder",
    reference: "AWS-APR",
  },
  {
    id: "bank_txn_hotel",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "suggested_match",
    sourceLineNumber: 22,
    transactionDate: "2026-04-05",
    amount: -320,
    currency: "GBP",
    merchant: "Harbour Hotel",
    description: "Conference accommodation",
    employee: "Ava Thompson",
    reference: "HTL-948",
  },
  {
    id: "bank_txn_team_lunch",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "unreconciled",
    sourceLineNumber: 25,
    transactionDate: "2026-04-06",
    amount: -84.5,
    currency: "GBP",
    merchant: "Canal Bistro",
    description: "Candidate lunch",
    employee: "Ava Thompson",
    reference: "BIS-840",
  },
  {
    id: "bank_txn_hotel_duplicate",
    bankStatementId: "stmt_april_cards",
    reconciliationStatus: "partially_matched",
    sourceLineNumber: 26,
    transactionDate: "2026-04-05",
    amount: -320,
    currency: "GBP",
    merchant: "Harbour Hotel",
    description: "Hotel duplicate on secondary card",
    employee: "Ava Thompson",
    reference: "HTL-949",
  },
];

const templates: MappingTemplate[] = [
  {
    id: "tpl_pleo_csv",
    name: "Pleo card export",
    sourceType: "csv",
    columnMappings: {
      date: "Transaction Date",
      amount: "Amount",
      merchant: "Merchant",
      description: "Description",
      employee: "Employee",
      currency: "Currency",
      reference: "Reference",
    },
  },
  {
    id: "tpl_generic_bank",
    name: "Generic card statement",
    sourceType: "xlsx",
    columnMappings: {
      date: "Date",
      amount: "Amount",
      merchant: "Payee",
      description: "Memo",
      currency: "Currency",
      reference: "Reference",
    },
  },
];

const bankStatements: BankStatement[] = [
  {
    id: "stmt_april_cards",
    name: "April card statement",
    fileName: "april-card-export.csv",
    bankName: "Corporate card feed",
    accountName: "Northstar card account",
    currency: "GBP",
    importedAt: "2026-04-07T14:20:00.000Z",
    importStatus: "imported",
    dateRangeStart: "2026-04-01",
    dateRangeEnd: "2026-04-30",
    transactionCount: aprilBankTransactions.length,
    previewHeaders: [
      "Transaction Date",
      "Amount",
      "Merchant",
      "Description",
      "Employee",
      "Currency",
      "Reference",
    ],
    savedColumnMappings: templates[0].columnMappings,
    transactions: aprilBankTransactions,
  },
];

const glRules: GlCodeRule[] = [
  {
    id: "gl_meals",
    glCode: "6105",
    label: "Travel and meals",
    keywordPattern: "cafe|coffee|restaurant|lunch|dinner",
    priority: 10,
  },
  {
    id: "gl_software",
    glCode: "7200",
    label: "Software subscriptions",
    keywordPattern: "software|subscription|saas|cloud",
    priority: 20,
  },
  {
    id: "gl_taxis",
    glCode: "6110",
    label: "Ground transport",
    supplierPattern: "uber|bolt|free now",
    priority: 15,
  },
];

// Use driving school presets as the default category rules
const categoryRules: CategoryRule[] = DRIVING_SCHOOL_CATEGORIES;

const runFiles: UploadedFileMeta[] = [
  {
    id: "file_txn_april",
    fileName: "april-card-export.csv",
    originalName: "april-card-export.csv",
    mimeType: "text/csv",
    sizeBytes: 48192,
    fileKind: "transaction_file",
  },
  {
    id: "file_docs_zip",
    fileName: "receipts-april.zip",
    originalName: "receipts-april.zip",
    mimeType: "application/zip",
    sizeBytes: 3284120,
    fileKind: "archive",
  },
];

const runAudit: ReviewAction[] = [
  {
    id: "audit_1",
    runId: "run_april_close",
    actionType: "approve",
    createdAt: "2026-04-07T18:40:00.000Z",
    actorName: "Maya Chen",
    note: "Approved conference taxi charge.",
  },
  {
    id: "audit_2",
    runId: "run_april_close",
    actionType: "override_gl_code",
    createdAt: "2026-04-07T18:43:00.000Z",
    actorName: "Maya Chen",
    field: "glCode",
    beforeValue: "6105",
    afterValue: "6110",
  },
];

const runMatches: MatchDecision[] = [
  {
    id: "match_1",
    transactionId: "txn_uber",
    documentId: "doc_uber",
    status: "matched",
    score: 95,
    selected: true,
    rationale: {
      amountScore: 40,
      dateScore: 20,
      supplierScore: 18,
      filenameScore: 7,
      employeeScore: 5,
      currencyScore: 5,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["Exact amount match", "Supplier aligned with merchant"],
    },
  },
  {
    id: "match_2",
    transactionId: "txn_costa",
    documentId: "doc_costa",
    status: "matched",
    score: 93,
    selected: true,
    rationale: {
      amountScore: 40,
      dateScore: 18,
      supplierScore: 18,
      filenameScore: 8,
      employeeScore: 4,
      currencyScore: 5,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["Amount and date aligned"],
    },
  },
  {
    id: "match_3",
    transactionId: "txn_aws",
    documentId: "doc_aws",
    status: "probable_match",
    score: 72,
    selected: true,
    rationale: {
      amountScore: 28,
      dateScore: 15,
      supplierScore: 16,
      filenameScore: 5,
      employeeScore: 3,
      currencyScore: 5,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["Gross differs by 1.10 because of foreign exchange"],
    },
  },
  {
    id: "match_4",
    transactionId: "txn_hotel",
    documentId: "doc_hotel_a",
    status: "multiple_candidates",
    score: 64,
    selected: true,
    rationale: {
      amountScore: 30,
      dateScore: 18,
      supplierScore: 8,
      filenameScore: 3,
      employeeScore: 0,
      currencyScore: 5,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["Two hotel invoices carry the same amount"],
    },
  },
  {
    id: "match_5",
    transactionId: "txn_team_lunch",
    status: "unmatched",
    score: 0,
    selected: true,
    rationale: {
      amountScore: 0,
      dateScore: 0,
      supplierScore: 0,
      filenameScore: 0,
      employeeScore: 0,
      currencyScore: 0,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["No candidate document available"],
    },
  },
  {
    id: "match_6",
    transactionId: "txn_hotel_duplicate",
    documentId: "doc_hotel_a",
    status: "duplicate_suspected",
    score: 67,
    selected: true,
    rationale: {
      amountScore: 30,
      dateScore: 18,
      supplierScore: 8,
      filenameScore: 6,
      employeeScore: 0,
      currencyScore: 5,
      invoiceNumberScore: 0,
      referenceScore: 0,
      notes: ["Same receipt appears to cover two transactions"],
    },
  },
];

const run: ReconciliationRun = {
  id: "run_april_close",
  name: "April card reconciliation",
  status: "review_required",
  createdAt: "2026-04-07T14:20:00.000Z",
  processedAt: "2026-04-07T18:32:00.000Z",
  entity: "Northstar Holdings Ltd",
  countryProfile: "GB",
  defaultCurrency: "GBP",
  bankStatementId: "stmt_april_cards",
  bankSourceMode: "statement",
  bankSourceLabel: "April card statement",
  transactionFileName: "april-card-export.csv",
  previewHeaders: [
    "Transaction Date",
    "Amount",
    "Merchant",
    "Description",
    "Employee",
    "Currency",
    "Reference",
  ],
  savedColumnMappings: templates[0].columnMappings,
  uploadedFiles: runFiles,
  transactions: [
    {
      id: "txn_uber",
      sourceBankTransactionId: "bank_txn_uber",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 12,
      transactionDate: "2026-04-02",
      amount: 42.6,
      currency: "GBP",
      merchant: "Uber BV",
      description: "Client visit taxi",
      employee: "Maya Chen",
      reference: "UBR-7741",
      glCode: "6110",
      vatCode: "GB20",
      category: "Fuel",
    },
    {
      id: "txn_costa",
      sourceBankTransactionId: "bank_txn_costa",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 13,
      transactionDate: "2026-04-02",
      amount: 6.4,
      currency: "GBP",
      merchant: "Costa Coffee",
      description: "Team coffee before client workshop",
      employee: "Maya Chen",
      reference: "CST-281",
      glCode: "6105",
      vatCode: "GB20",
      category: "Advertising",
    },
    {
      id: "txn_aws",
      sourceBankTransactionId: "bank_txn_aws",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 17,
      transactionDate: "2026-04-04",
      amount: 91.12,
      currency: "USD",
      merchant: "Amazon Web Services",
      description: "Monthly hosting",
      employee: "No cardholder",
      reference: "AWS-APR",
      glCode: "7200",
      category: "Software & Subscriptions",
    },
    {
      id: "txn_hotel",
      sourceBankTransactionId: "bank_txn_hotel",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 22,
      transactionDate: "2026-04-05",
      amount: 320,
      currency: "GBP",
      merchant: "Harbour Hotel",
      description: "Conference accommodation",
      employee: "Ava Thompson",
      reference: "HTL-948",
      // No category — shows as uncategorised in bookkeeping reports
    },
    {
      id: "txn_team_lunch",
      sourceBankTransactionId: "bank_txn_team_lunch",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 25,
      transactionDate: "2026-04-06",
      amount: 84.5,
      currency: "GBP",
      merchant: "Canal Bistro",
      description: "Candidate lunch",
      employee: "Ava Thompson",
      reference: "BIS-840",
      // No category — shows as uncategorised in bookkeeping reports
    },
    {
      id: "txn_hotel_duplicate",
      sourceBankTransactionId: "bank_txn_hotel_duplicate",
      bankStatementId: "stmt_april_cards",
      bankStatementName: "April card statement",
      sourceLineNumber: 26,
      transactionDate: "2026-04-05",
      amount: 320,
      currency: "GBP",
      merchant: "Harbour Hotel",
      description: "Hotel duplicate on secondary card",
      employee: "Ava Thompson",
      reference: "HTL-949",
      // No category — shows as uncategorised in bookkeeping reports
    },
  ],
  documents: [
    {
      id: "doc_uber",
      fileName: "uber-client-visit.pdf",
      supplier: "Uber",
      issueDate: "2026-04-02",
      gross: 42.6,
      net: 35.5,
      vat: 7.1,
      vatRateSummary: "20%",
      documentNumber: "INV-UBR-7741",
      countryCode: "GB",
      currency: "GBP",
      rawExtractedText: "Uber receipt INV-UBR-7741 total 42.60 VAT 7.10",
      confidence: 0.94,
      duplicateFingerprint: "uber-7741",
      taxLines: [
        {
          id: "tax_uber",
          label: "Standard",
          netAmount: 35.5,
          taxAmount: 7.1,
          grossAmount: 42.6,
          rate: 20,
          recoverable: true,
          vatCode: "GB20",
        },
      ],
    },
    {
      id: "doc_costa",
      fileName: "costa-02-apr.jpg",
      supplier: "Costa Coffee",
      issueDate: "2026-04-02",
      gross: 6.4,
      net: 5.33,
      vat: 1.07,
      vatRateSummary: "20%",
      documentNumber: "COSTA-APR-02",
      countryCode: "GB",
      currency: "GBP",
      rawExtractedText: "Costa coffee 6.40 VAT 1.07",
      confidence: 0.92,
      duplicateFingerprint: "costa-02-apr",
      taxLines: [
        {
          id: "tax_costa",
          label: "Food and drink",
          netAmount: 5.33,
          taxAmount: 1.07,
          grossAmount: 6.4,
          rate: 20,
          recoverable: true,
          vatCode: "GB20",
        },
      ],
    },
    {
      id: "doc_aws",
      fileName: "aws-april-invoice.pdf",
      supplier: "Amazon Web Services",
      issueDate: "2026-04-03",
      gross: 90.02,
      net: 90.02,
      vat: 0,
      vatRateSummary: "0%",
      documentNumber: "AWS-APR-2026",
      countryCode: "IE",
      currency: "USD",
      rawExtractedText: "AWS invoice subtotal 90.02 tax 0.00",
      confidence: 0.82,
      duplicateFingerprint: "aws-april-2026",
      taxLines: [
        {
          id: "tax_aws",
          label: "Reverse charge",
          netAmount: 90.02,
          taxAmount: 0,
          grossAmount: 90.02,
          rate: 0,
          recoverable: true,
          vatCode: "GB0",
        },
      ],
    },
    {
      id: "doc_hotel_a",
      fileName: "harbour-hotel-948.pdf",
      supplier: "Harbour Hotel",
      issueDate: "2026-04-05",
      gross: 320,
      net: 266.67,
      vat: 53.33,
      vatRateSummary: "20%",
      documentNumber: "HTL-948",
      countryCode: "GB",
      currency: "GBP",
      rawExtractedText: "Harbour Hotel total 320 VAT 53.33",
      confidence: 0.88,
      duplicateFingerprint: "harbour-948",
      taxLines: [
        {
          id: "tax_hotel_a",
          label: "Accommodation",
          netAmount: 266.67,
          taxAmount: 53.33,
          grossAmount: 320,
          rate: 20,
          recoverable: true,
          vatCode: "GB20",
        },
      ],
    },
    {
      id: "doc_hotel_b",
      fileName: "harbour-hotel-copy.png",
      supplier: "Harbour Hotel",
      issueDate: "2026-04-05",
      gross: 320,
      net: 266.67,
      vat: 53.33,
      vatRateSummary: "20%",
      documentNumber: "HTL-948-COPY",
      countryCode: "GB",
      currency: "GBP",
      rawExtractedText: "Harbour Hotel total 320 VAT 53.33",
      confidence: 0.48,
      duplicateFingerprint: "harbour-948",
      taxLines: [
        {
          id: "tax_hotel_b",
          label: "Accommodation",
          netAmount: 266.67,
          taxAmount: 53.33,
          grossAmount: 320,
          rate: 20,
          recoverable: true,
          vatCode: "GB20",
        },
      ],
    },
  ],
  matches: runMatches,
  auditTrail: runAudit,
  exports: [
    {
      id: "exp_1",
      format: "csv",
      fileName: "april-card-reconciliation.csv",
      createdAt: "2026-04-07T18:52:00.000Z",
    },
  ],
};

const secondRun: ReconciliationRun = {
  id: "run_march_close",
  name: "March AP reconciliation",
  status: "exported",
  createdAt: "2026-03-29T09:10:00.000Z",
  processedAt: "2026-03-29T10:20:00.000Z",
  entity: "Northstar Holdings Ltd",
  countryProfile: "GB",
  defaultCurrency: "GBP",
  transactionFileName: "march-ap.csv",
  previewHeaders: ["Date", "Amount", "Payee", "Memo", "Currency", "Reference"],
  savedColumnMappings: templates[1].columnMappings,
  uploadedFiles: [],
  transactions: [],
  documents: [],
  matches: [],
  auditTrail: [],
  exports: [
    {
      id: "exp_2",
      format: "xlsx",
      fileName: "march-ap-reconciled.xlsx",
      createdAt: "2026-03-29T10:24:00.000Z",
    },
  ],
};

export const demoStore = {
  user,
  workspace,
  vatRules,
  glRules,
  categoryRules,
  templates,
  bankStatements,
  runs: [run, secondRun],
};
